init:
  - git config --global core.autocrlf input

version: '{build}'

environment:
  matrix:
    - nodejs_version: '0.10'
    - nodejs_version: '0.11'

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm install

build: off

test_script:
  - ps: 'npm run-script test-node && npm run-script test-cli'
  - cmd: 'npm run-script test-node && npm run-script test-cli'
